name: Java Spring Boot CI/CD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # 1. Descarcă codul din repozitoriu
      - name: Extragere cod din GitHub
        uses: actions/checkout@v4

      # 2. Configurați Java JDK 17
      - name: Configurare JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3. Compilează proiectul local pe mașina GitHub (Generează fișierul .jar)
      - name: Compilare proiect cu Maven
        run: mvn clean package -DskipTests

      # 4. Transformă numele repozitoriului în litere mici (ca să nu mai avem eroarea de tag)
      - name: Setează numele repozitoriului în litere mici
        id: string
        run: |
          echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      # 5. Autentificare în GitHub Packages
      - name: Autentificare în GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 6. Construiește imaginea Docker folosind .jar-ul gata compilat și o trimite în cloud
      - name: Construire și Push Imagine Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LOWER }}/shopping-tracker:latest
            ghcr.io/${{ env.REPO_LOWER }}/shopping-tracker:${{ github.sha }}  
